### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by januridp** [django-id/website#2]
Salam kenal mas,

ini belum ada halaman error nya ya?

ketika user iseng ngecek http://www.django.id/thread/1/ lalu angkanya diganti suka suka maka not found muncul, tapi bukannya lebih baik di redirect aja ke halaman depan?

CMIIW

**Comment by alzearafat** [comment]
@januridp Salam kenal juga mas 

Iya, memang error page nya masih belum fix. Banyak miss sana-sini. Barusan aja saya fix-kan yang utk `403 Permission Denied`, tapi yang lain belum.

Thanks udah bantu ingetin! 👍
