### ISSUE TITLE
github scope permission?

### ISSUE THREAD

**Issue by Keda87** [django-id/website#4]
Hi mas @alzearafat ,
baru coba di local development untuk auth, sepertinya scope permission nya gak perlu untuk untuk dapet `write` permission di repo termasuk private repo. Untuk hindari penyalahgunaan.

Kalo diliat dari `settings.py` template.
```
SOCIALACCOUNT_PROVIDERS = {
    'github': {
        'SCOPE': [
            'user',
            'repo',
            'read:org',
        ],
    }
}
```
bisa diganti ke.
```
SOCIALACCOUNT_PROVIDERS = {
    'github': {
        'SCOPE': [
            `user:email'
        ],
    }
}
```

Referensi:
- https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-scopes-for-oauth-apps/
- http://django-allauth.readthedocs.io/en/latest/providers.html#github

**Comment by alzearafat** [comment]
Halo

Thanks mas @Keda87 . Iya, di production sudah sy revisi, tapi utk template settings.py nya belum. Lupa 😄 

Thanks udah di ingetin
