### ISSUE TITLE
provide settings.py?

### ISSUE THREAD

**Issue by Keda87** [django-id/website#5]
Hi mas @alzearafat,
baru cek travis-ci buat PR #3 ternyata belum jalan gara2 di repo gak ada file `settings.py` soalnya sengaja di ignore.
Traceback: https://travis-ci.org/Keda87/website/builds/288395754

Kira2 perlu bikin file settings khusus test apa gak ya?

Jadi opsi ada 2:
- Pake `local_settings.py`:
Jadi main `settings.py` tetep di push di repo, untuk beberapa variable yg kritis semacam `SECRET_KEY` bisa di override di `local_settings.py`, ataupun mungkin temen2 yg lain mau pake database lain di masing2 laptopnya, cukup override `local_settings.py`.
Untuk `local_settings.py` ini bakal di ignore dan gak akan di push di repo.

- Bikin `settings.py` khusus untuk test.
Let say namanya `test_settings.py` isinya clone dari `settings.py` yang dipake cuma di travis-ci aja.
Jadi jalanin testnya `$ python manage.py test --settings=djangoid.test_settings`

Atau mungkin ada cara lain?

**Comment by alzearafat** [comment]
Halo mas @Keda87 

Kayak nya emang mending bikin settings.py khusus test aja. Sy push nanti `test_settings.py` nya

Thanks!

**Comment by alzearafat** [comment]
Done mas @Keda87 👍

**Comment by Keda87** [comment]
Thanks!
Nanti kalo luang coba sempetin test lagi

**Comment by Keda87** [comment]
Done #8 , mungkin udah bisa di closed.
Thanks!
